<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-06-01">

<title>pyMETRIC-UAV: Getting Started</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="pyMETRIC_UAV_getting_started_files/libs/clipboard/clipboard.min.js"></script>
<script src="pyMETRIC_UAV_getting_started_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="pyMETRIC_UAV_getting_started_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="pyMETRIC_UAV_getting_started_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="pyMETRIC_UAV_getting_started_files/libs/quarto-html/popper.min.js"></script>
<script src="pyMETRIC_UAV_getting_started_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pyMETRIC_UAV_getting_started_files/libs/quarto-html/anchor.min.js"></script>
<link href="pyMETRIC_UAV_getting_started_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pyMETRIC_UAV_getting_started_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pyMETRIC_UAV_getting_started_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pyMETRIC_UAV_getting_started_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pyMETRIC_UAV_getting_started_files/libs/bootstrap/bootstrap-a74871fe4945b66d259aafc266475145.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#what-you-need-before-starting" id="toc-what-you-need-before-starting" class="nav-link active" data-scroll-target="#what-you-need-before-starting"><span class="header-section-number">1</span> What you need before starting</a></li>
  <li><a href="#one-time-environment-setup" id="toc-one-time-environment-setup" class="nav-link" data-scroll-target="#one-time-environment-setup"><span class="header-section-number">2</span> One-time environment setup</a></li>
  <li><a href="#confirming-the-example-dataset-is-in-place" id="toc-confirming-the-example-dataset-is-in-place" class="nav-link" data-scroll-target="#confirming-the-example-dataset-is-in-place"><span class="header-section-number">3</span> Confirming the example dataset is in place</a></li>
  <li><a href="#running-the-notebook" id="toc-running-the-notebook" class="nav-link" data-scroll-target="#running-the-notebook"><span class="header-section-number">4</span> Running the notebook</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">4.1</span> Setup</a></li>
  <li><a href="#pre-flight" id="toc-pre-flight" class="nav-link" data-scroll-target="#pre-flight"><span class="header-section-number">4.2</span> Pre-flight</a></li>
  <li><a href="#run" id="toc-run" class="nav-link" data-scroll-target="#run"><span class="header-section-number">4.3</span> Run</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.4</span> Summary</a></li>
  <li><a href="#diagnostics-optional" id="toc-diagnostics-optional" class="nav-link" data-scroll-target="#diagnostics-optional"><span class="header-section-number">4.5</span> Diagnostics (optional)</a></li>
  <li><a href="#sensitivity-optional" id="toc-sensitivity-optional" class="nav-link" data-scroll-target="#sensitivity-optional"><span class="header-section-number">4.6</span> Sensitivity (optional)</a></li>
  </ul></li>
  <li><a href="#what-you-get" id="toc-what-you-get" class="nav-link" data-scroll-target="#what-you-get"><span class="header-section-number">5</span> What you get</a></li>
  <li><a href="#running-your-own-flight" id="toc-running-your-own-flight" class="nav-link" data-scroll-target="#running-your-own-flight"><span class="header-section-number">6</span> Running your own flight</a></li>
  <li><a href="#troubleshooting" id="toc-troubleshooting" class="nav-link" data-scroll-target="#troubleshooting"><span class="header-section-number">7</span> Troubleshooting</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="pyMETRIC_UAV_getting_started.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">pyMETRIC-UAV: Getting Started</h1>
<p class="subtitle lead">Initial setup and a working example</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This guide walks a first-time user from a clean computer to a finished evapotranspiration (ET) map, using the bundled <strong>Fruita_Example</strong> dataset. It assumes no prior Python experience: you create the software environment once, then open one notebook and run it top to bottom.</p>
<p>For the science behind the model, the configuration reference, and the validation against the reference <code>WSWUP/pyMETRIC</code> code, see the companion <code>pyMETRIC_UAV_overview.pdf</code> document.</p>
<section id="what-you-need-before-starting" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> What you need before starting</h1>
<ul>
<li>The <strong>project folder</strong> (the directory that contains <code>pyMETRIC/</code>, <code>pyMETRIC_Batch_Run.ipynb</code>, <code>environment.yml</code>, and <code>Batch_Data/</code>). Keep this folder intact — the notebook loads its model code directly from the bundled <code>pyMETRIC/</code> subfolder.</li>
<li><strong>Miniconda or Anaconda</strong> installed. If you do not have it, install Miniconda from <a href="https://docs.conda.io/en/latest/miniconda.html" class="uri">https://docs.conda.io/en/latest/miniconda.html</a>. This is the only software you install by hand.</li>
</ul>
<p>You will use a terminal <strong>once</strong> to create the environment. After that, everything happens inside the notebook.</p>
</section>
<section id="one-time-environment-setup" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> One-time environment setup</h1>
<p>The project ships an <code>environment.yml</code> that pins every package to the versions the model was developed and validated against (Python 3.10, GDAL 3.11, pyTSEB 2.1, and the scientific stack). Creating the environment from this file is the only setup step.</p>
<p>Open a terminal (on Windows, use the <strong>Anaconda Prompt</strong>), change the directory to the project folder where <code>pymetric-uav</code> is located, and run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> env create <span class="at">-f</span> environment.yml</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">conda</span> activate pymetric-uav</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The first command downloads and installs everything; it can take several minutes. The second activates the environment so the next commands use it.</p>
<blockquote class="blockquote">
<p><strong>Note.</strong> GDAL (the geospatial library) is installed from <code>conda-forge</code> by the environment file. Do <strong>not</strong> try to install GDAL with <code>pip</code> — mixing the two is the most common cause of a broken environment.</p>
</blockquote>
<p>Then launch Jupyter from the same terminal:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">jupyter</span> lab</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This opens Jupyter in your web browser. In the file panel on the left, double-click <strong><code>pyMETRIC_Batch_Run.ipynb</code></strong> to open the notebook.</p>
<blockquote class="blockquote">
<p><strong>You only do this once.</strong> After the environment exists, future sessions are just: <code>conda activate pymetric-uav</code>, then <code>jupyter lab</code>. You do not recreate the environment or install anything again.</p>
</blockquote>
</section>
<section id="confirming-the-example-dataset-is-in-place" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Confirming the example dataset is in place</h1>
<p>The notebook processes whatever dataset folders it finds in <code>Batch_Data/</code>. The project ships with one example ready to go:</p>
<pre><code>Batch_Data/
  Fruita_Example/
    config.txt                 site, meteorology, and band assignments
    example_image_clipped.tif  the multiband UAV image (reflectance + thermal)
    Input/                     endmember / study-plot polygons (and derived
                               rasters, created on the first run)
    Output/                    results land here</code></pre>
<p><code>config.txt</code> is the file you edit for your own flights. For Fruita it is already filled in. The values that matter most are the acquisition time and the weather at the time of the UAV flight(s):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 28%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Setting</th>
<th style="text-align: left;">Value</th>
<th style="text-align: left;">Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>DOY</code> / <code>time</code></td>
<td style="text-align: left;">221 / 10.5</td>
<td style="text-align: left;">Aug 9, 10:30 AM local standard time</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>T_A1</code></td>
<td style="text-align: left;">27.38 °C</td>
<td style="text-align: left;">air temperature at the flight</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>u</code></td>
<td style="text-align: left;">1.63 m/s</td>
<td style="text-align: left;">wind speed</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>S_dn</code></td>
<td style="text-align: left;">528.25 W/m²</td>
<td style="text-align: left;">incoming shortwave radiation</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>crop_type</code></td>
<td style="text-align: left;"><code>alfalfa</code></td>
<td style="text-align: left;">selects the alfalfa canopy preset</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>reference_type</code></td>
<td style="text-align: left;"><code>tall</code></td>
<td style="text-align: left;">alfalfa (ETr) reference surface</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>endmember_mode</code></td>
<td style="text-align: left;"><code>zone</code></td>
<td style="text-align: left;">restrict hot/cold search to the drawn polygons</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>endmember_search</code></td>
<td style="text-align: left;"><code>2</code></td>
<td style="text-align: left;">Min/Max (percentile-based) selector</td>
</tr>
</tbody>
</table>
</section>
<section id="running-the-notebook" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Running the notebook</h1>
<p>The notebook contains six cells. Run them in order (<strong>Shift+Enter</strong> runs the current cell and moves to the next, or use <em>Run → Run All Cells</em>). Each cell print a log and a record of any generated output, so you can confirm progress as you go.</p>
<section id="setup" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">4.1</span> Setup</h2>
<p>The first cell imports the libraries and loads the model code from the bundled <code>pyMETRIC/</code> folder. A successful run prints something like:</p>
<pre><code>pyMETRIC-batch v4.0.0
Using bundled pyMETRIC: .../pyMETRIC-uav/pyMETRIC
Base directory:  .../pyMETRIC-uav
Batch directory: .../pyMETRIC-uav/Batch_Data (exists: True)</code></pre>
<p>The line <strong><code>Using bundled pyMETRIC</code></strong> confirms the notebook is running this folder’s model code, not some other copy of pyMETRIC that might be installed on the machine. If instead the cell stops with an error saying it is “NOT running the bundled code,” the project folder layout has been disturbed — make sure <code>pyMETRIC/</code> sits next to the notebook, then restart the kernel (<em>Kernel → Restart Kernel</em>) and run this cell first.</p>
</section>
<section id="pre-flight" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="pre-flight"><span class="header-section-number">4.2</span> Pre-flight</h2>
<p>The second cell scans <code>Batch_Data/</code>, checks each dataset’s configuration, and reports which are ready. For the Fruita_Example, you should see it marked <strong>READY</strong>. You should also see a config sanity check that echoes the acquisition date in plain English (and warns if any met value looks unusual):</p>
<pre><code>=== Preflight Check ===
  [Fruita_Example] READY — multiband: example_image_clipped.tif (config: config.txt)

1/1 datasets ready for processing.

=== Config sanity check ===
  Acquisition: DOY 221, 10.50 hr -&gt; Aug 9 at 10:30 (local standard time)</code></pre>
<p>Nothing is processed yet — this is the safety check.</p>
</section>
<section id="run" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="run"><span class="header-section-number">4.3</span> Run</h2>
<p>The third cell does the actual work. For each ready dataset, this cell:</p>
<ol type="1">
<li>Derives NDVI, leaf area index (LAI), fractional cover, and surface temperature (TRAD) from the multiband image and exports each surface to the <code>Input/</code> directory;</li>
<li>Runs the METRIC energy-balance model;</li>
<li>Converts latent heat to instantaneous ET (mm/hr);</li>
<li>Computes the ASCE reference ET for the scene; and</li>
<li>Computes per-plot zonal statistics from the study-plot polygons.</li>
</ol>
<p>A plot is provided that indicates the two anchor (endmember) pixels and the resulting near-surface temperature-gradient line. For the Fruita_Example, the run reports:</p>
<pre><code>Cold pixel at (554, 376): 293.80 K, 0.929 VI
Hot pixel  at (28, 299):  321.85 K, 0.118 VI
Endmember quality OK: LST range = 28.0 K, cold VI = 0.93, hot VI = 0.12
Calibrated dT: a=-27.740023, b=0.095559
  ET mean = 0.2279 mm/hr
  ETr = 0.5267 mm/hr</code></pre>
<p>This output indicates selection of a well-watered alfalfa <strong>cold</strong> pixel near 294 K and a hot bare-soil pixel near 322 K, The image-mean instantaneous ET is <strong>0.228 mm/hr</strong>, and the ASCE alfalfa reference ET is <strong>0.527 mm/hr</strong>. The scene averages about 43% of reference, consistent with a mix of irrigated alfalfa and bare ground.</p>
</section>
<section id="summary" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="summary"><span class="header-section-number">4.4</span> Summary</h2>
<p>The fourth cell prints a table with one row per dataset in the <code>Batch/</code> directory. Each row contains values for processing status, mean ET, reference ET (ETr), the ET / ETr ratio, and the number of study plots. For the Fruita_Example, it reads:</p>
<pre><code>=== Batch Summary ===
       Dataset  Status  Mean ET (mm/hr)  Ref ETr (mm/hr)  ET / ETr  Plots
Fruita_Example SUCCESS           0.2279           0.5267     0.433     24</code></pre>
<p>This table provides a quick “did it work and are the numbers sensible” check.</p>
</section>
<section id="diagnostics-optional" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="diagnostics-optional"><span class="header-section-number">4.5</span> Diagnostics (optional)</h2>
<p>The fifth cell prints per-raster statistics (min/max/mean/std and NaN counts) for the derived inputs. These outputs are useful if a result looks off and you want to see whether NDVI, LAI, and TRAD came out in a plausible range. For the Fruita_Example, TRAD runs between 293–330 K, NDVI is between 0.03–0.94, and LAI is between 0–7.7. Each includes roughly 6.5% of pixels masked as no-data.</p>
</section>
<section id="sensitivity-optional" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="sensitivity-optional"><span class="header-section-number">4.6</span> Sensitivity (optional)</h2>
<p>The sixth cell re-runs the scene under several endmember-selection strategies (Min/Max, CIMEC, ESA; with and without the zone polygons) and writes a small table comparing the image-mean ET each one produces. It quantifies how much the answer depends on how the hot/cold pixels are selected. For the Fruita_Example, the five strategies span roughly 0.18–0.24 mm/hr. This cell is optional and takes longer to run because it processes each scene several times.</p>
</section>
</section>
<section id="what-you-get" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> What you get</h1>
<p>After a successful run, <code>Batch_Data/Fruita_Example/Output/</code> contains:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 62%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">File</th>
<th style="text-align: left;">Contents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Fruita_Example_METRIC.tif</code></td>
<td style="text-align: left;">4-band raster: net radiation <span class="math inline">\(R_n\)</span>, sensible heat <span class="math inline">\(H\)</span>, latent heat <span class="math inline">\(LE\)</span>, soil heat flux <span class="math inline">\(G\)</span> (all W/m²)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Fruita_Example_ET_mm_hour.tif</code></td>
<td style="text-align: left;">instantaneous ET (mm/hr) — the headline map</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Fruita_Example_METRIC_ancillary.tif</code></td>
<td style="text-align: left;">supporting bands (aerodynamic resistance, reference ET, ET fraction, quality flag, …)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Fruita_Example_Penman_ET.csv</code></td>
<td style="text-align: left;">the scene’s ASCE reference ET</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>Fruita_Example_Zonal_Stats.csv</code></td>
<td style="text-align: left;">per-study-plot ET and ET-fraction statistics</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Fruita_Example_log.txt</code></td>
<td style="text-align: left;">a full text log of the run</td>
</tr>
</tbody>
</table>
<p>The ET map and the per-plot CSV are usually what you came for. Open the <code>*_ET_mm_hour.tif</code> in any GIS (QGIS, ArcGIS) to view the ET map; open the <code>*_Zonal_Stats.csv</code> in a spreadsheet.</p>
</section>
<section id="running-your-own-flight" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Running your own flight</h1>
<p>To process your own UAV scene instead of the Fruita_Example:</p>
<ol type="1">
<li>Make a new folder inside <code>Batch_Data/</code> (e.g.&nbsp;<code>Batch_Data/MyField/</code>).</li>
<li>Put your multiband image in it and copy <code>config_template.txt</code> to <code>MyField/config.txt</code>. The configuration file is documented in full in the companion overview (<em>Configuration</em> section); start from the annotated <code>config_template.txt</code> and change one section at a time.</li>
<li>Edit <code>config.txt</code>. At minimum, edit the band assignments, the acquisition <code>DOY</code>/<code>time</code>, the four met values (<code>T_A1</code>, <code>u</code>, <code>ea</code>, <code>S_dn</code>), the site <code>lat</code>/<code>lon</code>/<code>alt</code>, and the <code>crop_type</code>. The template is annotated section by section.</li>
<li>(Optional) Provide hot/cold zone polygons and study-plot polygons in an <code>Input/</code> subfolder, and set <code>endmember_mode=zone</code>.</li>
<li>Run the notebook exactly as above. It will pick up every ready dataset in <code>Batch_Data/</code>, including the Fruita_Example and any additional sets you added.</li>
<li>Once you are satisfied with the model results from one or more datasets, move those directories to a different location (e.g.&nbsp;<code>Batch_Data/MyField/</code> → <code>Processed_Data/MyField/</code>) so that the model does reprocess them each time you add a new dataset.</li>
</ol>
</section>
<section id="troubleshooting" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Troubleshooting</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 68%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Symptom</th>
<th style="text-align: left;">Likely cause / fix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Setup cell errors: “NOT running the bundled code”</td>
<td style="text-align: left;"><code>pyMETRIC/</code> is not next to the notebook. Restore the folder layout; restart the kernel; run the Setup cell first.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>conda env create</code> fails</td>
<td style="text-align: left;">Make sure you ran it from the project folder (where <code>environment.yml</code> lives) and that conda is installed. Re-run; transient download failures are common.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GDAL / <code>osgeo</code> import error</td>
<td style="text-align: left;">The environment did not build correctly. Recreate it from <code>environment.yml</code>; do not <code>pip install gdal</code>.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pre-flight marks a dataset NOT READY</td>
<td style="text-align: left;">A required file or <code>config.txt</code> key is missing; the preflight message names which one.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ET map is mostly zero or NaN</td>
<td style="text-align: left;">Check the Diagnostics cell — usually a bad band assignment (wrong red/NIR/thermal band number) or out-of-range surface temperatures.</td>
</tr>
</tbody>
</table>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>